[package]
name = "smallvec"
version = "1.1.0"
edition = "2018"
authors = ["Simon Sapin <simon.sapin@exyr.org>"]
license = "MIT/Apache-2.0"
repository = "https://github.com/servo/rust-smallvec"
description = "'Small vector' optimization: store up to a small number of items on the stack"
keywords = ["small", "vec", "vector", "stack", "no_std"]
categories = ["data-structures"]
readme = "README.md"
documentation = "https://docs.rs/smallvec/"

[features]
write = []
union = []
specialization = []
may_dangle = []
default = ["mesalock_sgx"]
mesalock_sgx = ["sgx_tstd"]

[lib]
name = "smallvec"
path = "lib.rs"

[dependencies]
serde = { version = "1", git = "https://github.com/mesalock-linux/serde-sgx", optional = true }
sgx_tstd = { rev = "v1.1.2", git = "https://github.com/apache/teaclave-sgx-sdk.git", optional = true }

[dev_dependencies]
#bincode = "1.0.1"
